const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openFolder: () => ipcRenderer.invoke('dialog:openFolder'),
  getRecentProjects: () => ipcRenderer.invoke('store:getRecentProjects'),
  readDirectory: (path) => ipcRenderer.invoke('fs:readDirectory', path),
  readFile: (path) => ipcRenderer.invoke('fs:readFile', path),
  readFileBinary: (path) => ipcRenderer.invoke('fs:readFileBinary', path),
  openInExplorer: (path) => ipcRenderer.invoke('fs:openInExplorer', path),
  // Workspace APIs
  workspaceGetAll: () => ipcRenderer.invoke('workspace:getAll'),
  workspaceSave: (workspaces) => ipcRenderer.invoke('workspace:save', workspaces),
  workspaceGetActive: () => ipcRenderer.invoke('workspace:getActive'),
  workspaceSetActive: (workspaceId) => ipcRenderer.invoke('workspace:setActive', workspaceId),
  workspaceClear: () => ipcRenderer.invoke('workspace:clear'),
  workspaceGetLastSession: () => ipcRenderer.invoke('workspace:getLastSession'),
  workspaceRestoreSession: () => ipcRenderer.invoke('workspace:restoreSession'),
  // Terminal APIs
  terminalCreate: (opts) => ipcRenderer.invoke('terminal:create', opts),
  terminalWrite: (opts) => ipcRenderer.invoke('terminal:write', opts),
  terminalResize: (opts) => ipcRenderer.invoke('terminal:resize', opts),
  terminalKill: (opts) => ipcRenderer.invoke('terminal:kill', opts),
  onTerminalData: (callback) => ipcRenderer.on('terminal:data', (event, data) => callback(data)),
  onTerminalExit: (callback) => ipcRenderer.on('terminal:exit', (event, data) => callback(data)),
  // LSP APIs
  lspStartServer: (opts) => ipcRenderer.invoke('lsp:startServer', opts),
  lspSendMessage: (opts) => ipcRenderer.invoke('lsp:sendMessage', opts),
  lspStopServer: (opts) => ipcRenderer.invoke('lsp:stopServer', opts),
  onLspMessage: (callback) => ipcRenderer.on('lsp:message', (event, data) => callback(data)),
  // Browser APIs
  browserCreate: (opts) => ipcRenderer.invoke('browser:create', opts),
  browserSetBounds: (opts) => ipcRenderer.invoke('browser:setBounds', opts),
  browserHide: (opts) => ipcRenderer.invoke('browser:hide', opts),
  browserNavigate: (opts) => ipcRenderer.invoke('browser:navigate', opts),
  browserGoBack: (opts) => ipcRenderer.invoke('browser:goBack', opts),
  browserGoForward: (opts) => ipcRenderer.invoke('browser:goForward', opts),
  browserReload: (opts) => ipcRenderer.invoke('browser:reload', opts),
  browserStop: (opts) => ipcRenderer.invoke('browser:stop', opts),
  browserDestroy: (opts) => ipcRenderer.invoke('browser:destroy', opts),
  browserFocus: (opts) => ipcRenderer.invoke('browser:focus', opts),
  onBrowserNavigation: (callback) => ipcRenderer.on('browser:navigation', (event, data) => callback(data)),
  onBrowserTitle: (callback) => ipcRenderer.on('browser:title', (event, data) => callback(data)),
  onBrowserLoading: (callback) => ipcRenderer.on('browser:loading', (event, data) => callback(data)),
  onBrowserError: (callback) => ipcRenderer.on('browser:error', (event, data) => callback(data)),
  onBrowserKeyboardNav: (callback) => ipcRenderer.on('browser:keyboard-nav', (event, data) => callback(data)),
  onBrowserOpenInTab: (callback) => ipcRenderer.on('browser:open-in-tab', (event, data) => callback(data)),
  // Overlay management
  browsersHideForOverlay: () => ipcRenderer.invoke('browsers:hideForOverlay'),
  browsersShowAfterOverlay: () => ipcRenderer.invoke('browsers:showAfterOverlay'),
  onBrowsersRepositionAfterOverlay: (callback) => ipcRenderer.on('browsers:repositionAfterOverlay', () => callback()),
  // Workspace browser management
  browsersHideWorkspace: (workspaceId) => ipcRenderer.invoke('browsers:hideWorkspace', { workspaceId }),
  browsersShowWorkspace: (workspaceId) => ipcRenderer.invoke('browsers:showWorkspace', { workspaceId }),
  // Mind file APIs
  mindList: (workspacePath) => ipcRenderer.invoke('mind:list', workspacePath),
  mindRead: (opts) => ipcRenderer.invoke('mind:read', opts),
  mindWrite: (opts) => ipcRenderer.invoke('mind:write', opts),
  mindDelete: (opts) => ipcRenderer.invoke('mind:delete', opts),
  // Git APIs
  gitStatus: (opts) => ipcRenderer.invoke('git:status', opts),
  gitBranches: (opts) => ipcRenderer.invoke('git:branches', opts),
  gitLog: (opts) => ipcRenderer.invoke('git:log', opts),
  gitAdd: (opts) => ipcRenderer.invoke('git:add', opts),
  gitReset: (opts) => ipcRenderer.invoke('git:reset', opts),
  gitCommit: (opts) => ipcRenderer.invoke('git:commit', opts),
  gitCheckout: (opts) => ipcRenderer.invoke('git:checkout', opts),
  gitDiff: (opts) => ipcRenderer.invoke('git:diff', opts),
  gitPull: (opts) => ipcRenderer.invoke('git:pull', opts),
  gitPush: (opts) => ipcRenderer.invoke('git:push', opts),
  // SSH APIs
  sshGetConnections: () => ipcRenderer.invoke('ssh:getConnections'),
  sshSaveConnection: (opts) => ipcRenderer.invoke('ssh:saveConnection', opts),
  sshUpdateConnection: (opts) => ipcRenderer.invoke('ssh:updateConnection', opts),
  sshRemoveConnection: (id) => ipcRenderer.invoke('ssh:removeConnection', id),
  sshClearAllConnections: () => ipcRenderer.invoke('ssh:clearAllConnections'),
  sshSetTempCredentials: (opts) => ipcRenderer.invoke('ssh:setTempCredentials', opts),
  sshTestConnection: (connection, credentials) => ipcRenderer.invoke('ssh:testConnection', { connection, credentials }),
  sshSelectKeyFile: () => ipcRenderer.invoke('ssh:selectKeyFile'),
  sshCreateTerminal: (opts) => ipcRenderer.invoke('ssh:createTerminal', opts),
  sshWrite: (opts) => ipcRenderer.invoke('ssh:write', opts),
  sshResize: (opts) => ipcRenderer.invoke('ssh:resize', opts),
  sshKill: (opts) => ipcRenderer.invoke('ssh:kill', opts),
  // SFTP APIs
  sshSftpReadDir: (connectionId, remotePath) => ipcRenderer.invoke('ssh:sftp:readdir', { connectionId, remotePath }),
  sshSftpReadFile: (connectionId, remotePath) => ipcRenderer.invoke('ssh:sftp:readFile', { connectionId, remotePath }),
  sshSftpReadFileBinary: (connectionId, remotePath) => ipcRenderer.invoke('ssh:sftp:readFileBinary', { connectionId, remotePath }),
  sshSftpWriteFile: (connectionId, remotePath, content) => ipcRenderer.invoke('ssh:sftp:writeFile', { connectionId, remotePath, content }),
  sshSftpMkdir: (connectionId, remotePath) => ipcRenderer.invoke('ssh:sftp:mkdir', { connectionId, remotePath }),
  sshSftpUnlink: (connectionId, remotePath) => ipcRenderer.invoke('ssh:sftp:unlink', { connectionId, remotePath }),
  sshSftpRmdir: (connectionId, remotePath) => ipcRenderer.invoke('ssh:sftp:rmdir', { connectionId, remotePath }),
  sshSftpRename: (connectionId, oldPath, newPath) => ipcRenderer.invoke('ssh:sftp:rename', { connectionId, oldPath, newPath }),
  sshSftpStat: (connectionId, remotePath) => ipcRenderer.invoke('ssh:sftp:stat', { connectionId, remotePath }),
});
